services:
  vpn_server:
    image: hwdsl2/ipsec-vpn-server
    container_name: ipsec-vpn-server
    ports:
      - 500:500/udp
      - 4500:4500/udp
    volumes:
      - ./ikev2-vpn-data:/etc/ipsec.d
      - /lib/modules:/lib/modules:ro
    privileged: true
    restart: always
